<?php
//Qui định đường dẩn các thự mục( css, img [hình ảnh tin tức, layout,....])
    define('L0','');
    define('L1','../');
    define('L2','../../');
    define('CSS','css/');
    define('JS','js/');
    define('IMG','img/');
    define('API','api/');
    define('LIB','lib/');
    define('VENDOR','vendor/');
    define('PAGES','pages/');
    define('US_COM','us_com/');
    define('FONTS','../vendor/fonts/');
    //admin
    define('AD_ADMIN','admin/');
    define('AD_CSS','css/');
    define('PAGES_AD',AD_ADMIN.'pages_ad/');
    define('AD_COM',AD_ADMIN.'ad_com/');
?>